#!/bin/bash

#TODO: command line options, help etc.
# -s suppress output?
#use: 
#getopts string name[args]
option=
if [ ! $@ ] 
	then
	echo 'usage: apt <files>'
	exit
fi

#if test $1 = -s
#	then
#	echo \$1 is $1
#	option= "1> /dev/null"
#fi
for each in $@
do
#	echo option is $option
#	apt360 <$each $option 
#	apt360 <$each #1> /dev/null
	apt360 <$each #1> /dev/null
#   temp.dxf temp.pmill
#mv temp.dxf $each.dxf 
# all: $each.dxf $each.pmill
done

