#!/bin/bash

#todo: command line options, help etc.
# -s suppress output?
#use: 
#getopts string name[args]
if [ ! $@ ] 
	then
	echo 'usage: apt <files>'
	exit
fi

for each in $@
do
	export APT_FILENAME=${each##*/} #for postproc's use
#	if [-x vapt]
#	then
#		echo in then
		apt360 <$each|vapt
#	else
#		echo in else
#		apt360 <$each #1> /dev/null

#	fi
done

