#!/bin/bash

#todo: command line options, help etc.
# -s suppress output?
#use: 
#getopts string name[args]
if [ ! $@ ] 
	then
	echo 'usage: apt <files>'
	exit
fi

for each in $@
do
	export APT_FILENAME=${each##*/} #for postproc's use
		apt360 <$each
done

