#!/bin/bash
#  Script to execute postprocessors
#  apt360 will call this script to execute the postprocessor given in a 
#  MACHIN statement.. $1 is the name of the first postprocessor; $2 is
#  the machine number; $3 and $4 are the next postprocessor and machine, 
#  respectively, and so on.
echo ....SECTN4 POST.....
for machins in $*
do

	case $machins
	in

	DXF)
	string=$string" -p dxf"	
	;;

	PMILL)
	string=$string" -p pmill"	
	;;
	[0-9]|[0-9][0-9])
	string=$string" -n"$machins	
	;;

	*)
		echo postprocessor:WARNING: Could not find post $machins
	esac


done
postp $string < cl.tap > ${APT_FILENAME%.apt}.tap


