#!/bin/bash
#  Script to execute postprocessors
#  apt360 will call this script to execute the postprocessor given in a 
#  MACHIN statement.. $1 is the name of the first postprocessor; $2 is
#  the machine number; $3 and $4 are the next postprocessor and machine, 
#  respectively, and so on.
echo ....SECTN4 POST.....
for machins in $*
do

	case $machins
	in

	[0-9]|[0-9][0-9])
	string=$string" -n"$machins	
	;;

	*)
	string=$string" -p "$machins	
	;;
	esac

done
echo ....calling postp with options $string
postp $string < cl.tap > ${APT_FILENAME%.apt}.tap


