#!/bin/bash
#  Script to execute postprocessors
#  apt360 will call this script to execute the postprocessor given in a 
#  MACHIN statement.. $1 is the name of the first postprocessor; $2 is
#  the machine number; $3 is the next postprocessor or machine, and so on.

function callpp 
{
	echo "....calling postp as:
\"postp $1 < cl.tap > ${APT_FILENAME%.apt}.$post$number.tap\""
	postp $1 < cl.tap > ${APT_FILENAME%.apt}.$post$number.tap
	echo
}


echo ....SECTN4 POST.....
echo
number=
post=
for machins in $*
do
	if [ -n "$(echo $machins|egrep '[0-9]+')" ]
	then
		nstr="-n$machins"
		number=$machins
		callpp "$pstr $nstr"

	else 
		post=$machins
		pstr="-p$machins"
	fi
	
done


